name: Test Publish NPM package to GitHub Packages
on:
  push:
    branches:
      - main
#    paths:
#      - 'storage/api-docs/api-docs.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [ 20.x ]
    steps:
      - name: Checkout repository changes
        uses: actions/checkout@v4

      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.3.0
        with:
          generator: typescript-fetch
          openapi-file: storage/api-docs/api-docs.json
          output-dir: storage/api-docs/tmp/
          command-args: '-c ts-gen-config.json --global-property skipFormModel=false --git-user-id "LeX142" --git-repo-id "test-openapi"'
      # Setup .npmrc file to publish to GitHub Packages
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        working-directory: storage/api-docs/tmp
        run: npm install

      - name: Build
        working-directory: storage/api-docs/tmp
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: storage/api-docs/tmp/

  publish:
    name: 'Publish package to Github.com'
    needs: build
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [ 20.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@LeX142'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: package
      - name: Publish package
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  #        run: |
#          npm ci
#          npm build
#          npm publish
#      - name: Publish package
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20.x'
#          registry-url: 'https://npm.pkg.github.com'
#          # Defaults to the user or organization that owns the workflow file
#          scope: '@LeX142/test-openapi'
#          run: |
#            cd storage/api-docs/tmp/
#            npm build
#            npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
