name: Test Publish NPM package to GitHub Packages
on:
  push:
    branches:
      - main
#    paths:
#      - 'storage/api-docs/api-docs.json'

jobs:
  generate-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository changes
        uses: actions/checkout@v4

      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.3.0
        with:
          generator: typescript-axios
          openapi-file: storage/api-docs/api-docs.json
          output-dir: /github/workspace/storage/api-docs/tmp/
      # Setup .npmrc file to publish to GitHub Packages
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@LeX142/test-openapi'
      - run: |
          ls -l /github/workspace/storage/api-docs/tmp/
          cd /github/workspace/storage/api-docs/tmp/
          npm ci
          npm build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Publish package
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20.x'
#          registry-url: 'https://npm.pkg.github.com'
#          # Defaults to the user or organization that owns the workflow file
#          scope: '@LeX142/test-openapi'
#          run: |
#            cd storage/api-docs/tmp/
#            npm build
#            npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
