name: Test Publish NPM package to GitHub Packages
on:
  push:
    branches:
      - main
#    paths:
#      - 'storage/api-docs/api-docs.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [ 20.x ]
    steps:
      - name: Checkout repository changes
        uses: actions/checkout@v4

      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.3.0
        with:
          generator: typescript-fetch
          openapi-file: storage/api-docs/api-docs.json
          output-dir: storage/api-docs/tmp/
          command-args: '-c ts-gen-config.json --global-property skipFormModel=false --git-user-id "lex142" --git-repo-id "test-openapi"'
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: storage/api-docs/tmp/

  publish:
    name: 'Publish package to Github.com'
    needs: build
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [ 20.x ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@LeX142'

      - uses: actions/download-artifact@v4
        with:
          name: package

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Publish package
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' ${{secrets.GITHUB_TOKEN}}
          npm config set @lex142:registry https://npm.pkg.github.com
          # sed -e 's/\"author\"\: \"OpenAPI-Generator\",/\"author\"\: \"OpenAPI-Generator\",\"publishConfig\"\: \{\"registry\"\: \"https\:\/\/npm.pkg.github.com\/\"\},/' package.json
          # cat package.json
          npm unpublish
          npm version patch
          npm publish
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
